version: '2'

services:
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: "bridge"
    restart: always

